### ISSUE TITLE
Add automated acceptance tests

### ISSUE THREAD

**Issue by OriHoch** [Kamatera/packer-plugin-kamatera#16]
e.g. https://github.com/hashicorp/packer-plugin-scaffolding/blob/main/.github/workflows/test-plugin-example.yml

Check Hashicorp guidelines to make sure we will pass their review - https://www.packer.io/docs/plugins/packer-integration-program#3-dev-test

**Comment by imcvampire** [comment]
This action - https://github.com/hashicorp/packer-plugin-scaffolding/blob/main/.github/workflows/test-plugin-example.yml - is triggered by hand because it needs `goreleaser` finishes first.

**Comment by OriHoch** [comment]
please have the acceptance test run automatically on every push to main branch

**Comment by imcvampire** [comment]
Acceptance test means the workflow above or just unit tests?

**Comment by OriHoch** [comment]
the workflow above

**Comment by imcvampire** [comment]
But it won't work until you create a tag and let `goreleaser` finishes its job. 

You can check other packers. All of them don't run it automatically https://github.com/hashicorp/packer-plugin-googlecompute/blob/main/.github/workflows/test-plugin-example.yml

**Comment by OriHoch** [comment]
for the packer-plugin-googlecompute they seem to run tests in circleci - https://github.com/hashicorp/packer-plugin-googlecompute/blob/main/.circleci/config.yml

Regarding our acceptance test - it should compile a binary for linux and then run the acceptance test on it (create an image)

**Comment by imcvampire** [comment]
@OriHoch The acceptance test runs automatically now after `goreleaser` finishes

**Comment by OriHoch** [comment]
please have the test run on every push to master - we should run the test before releasing
