### ISSUE TITLE
register the plugin documentation

### ISSUE THREAD

**Issue by OriHoch** [Kamatera/packer-plugin-kamatera#21]
https://www.packer.io/docs/plugins/creation#registering-plugin-documentation

**Comment by imcvampire** [comment]
`Documentation for a plugin is maintained within the docs directory and served on GitHub.` 

So we have to move back the documentation from `README.md` to `docs` or we have to maintain 2 versions?

**Comment by OriHoch** [comment]
please change to conform to the requirements, best not to maintain 2 versions
