### ISSUE TITLE
automated test should build and save an image to hard disk library

### ISSUE THREAD

**Issue by OriHoch** [Kamatera/packer-plugin-kamatera#26]
looks like the automated test is not building and saving an image

https://github.com/Kamatera/packer-plugin-kamatera/runs/3173745762

1. it's too fast (finished in 48 seconds)
2. output does not contain the expected output from the packer build

**Comment by imcvampire** [comment]
Fixed on https://github.com/Kamatera/packer-plugin-kamatera/commit/03c1c8f4e8cc4fc6e7485af57d973c0a69000231
