### ISSUE TITLE
file provisioner getting username/password error

### ISSUE THREAD

**Issue by strelok899** [Kamatera/packer-plugin-kamatera#47]
`==> kamatera.debian_11: Creating server ...
==> kamatera.debian_11: Waiting creation ...
==> kamatera.debian_11: Using SSH communicator to connect: 185.220.206.223
==> kamatera.debian_11: Waiting for SSH to become available...
==> kamatera.debian_11: Error waiting for SSH: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
==> kamatera.debian_11: Destroying server...
Build 'kamatera.debian_11' errored after 8 minutes 20 seconds: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

==> Wait completed after 8 minutes 20 seconds

==> Some builds didn't complete successfully and had errors:
--> kamatera.debian_11: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

==> Builds finished but no artifacts were created.`

the error happens using 

`provisioner "file" {
    source      = "foo.deb"
    destination = "/root/foo.deb"
  }`

**Comment by OriHoch** [comment]
Hi, thanks for the bug report, could you paste the full .hcl file you used?

**Comment by strelok899** [comment]
`source "kamatera" "debian_11" {
  datacenter    = "IL-RH"
  image         = "ubuntu_server_20.04_64-bit_optimized_updated"
  disk          = 10
  ssh_username  = "root"
  image_name    = "comet-backup-{{timestamp}}"
  api_client_id = "HHHHHHHHHH"
  api_secret    = "JJJJJJJJJJJJJJ"
}


build {
  sources = [
    "source.kamatera.debian_11"
  ]
  provisioner "file" {
    source      = "cometd_22.5.3_amd64.deb"
    destination = "/root/cometd_22.5.3_amd64.deb"
  }
  provisioner "shell" {
    environment_vars = [

    ]
    inline = [
      "cd /root",
      "dpkg -i cometd_22.5.3_amd64.deb ; apt-get -f install",
    ]
  }
}`

**Comment by OriHoch** [comment]
thanks, could you also write the version of Packer you are using and the version of the kamatera packer plugin you are using?

**Comment by strelok899** [comment]
Packer v1.8.3
packer-plugin-kamatera_v0.4.0_x5.0_windows_amd64.exe

**Comment by OriHoch** [comment]
I made some changes, so you should try latest version of packer-plugin-kamatera v0.5.4, it includes better debugging details, so if you encounter more problems, please include full log.

There were some communications problems in Kamatera recently so they might also be related to your problems.

I currently managed to run similar provisioning script fine.

feel free to reopen the issue if you keep having problems..
