### ISSUE TITLE
map json api error 400 when using debioan image

### ISSUE THREAD

**Issue by strelok899** [Kamatera/packer-plugin-kamatera#48]
when using debian 

`source "kamatera" "debian_11" {
  datacenter    = "IL-RH"
  image         = "debian_11.4_64-bit"
  disk          = 10
  ssh_username  = "root"
  image_name    = "comet-backup-{{timestamp}}"
  api_client_id = "HHHHHHHHHHHH"
  api_secret    = "JJJJJJJJJJJJJJJ"
}`

getting error 

` packer build .\comet-backup.pkr.hcl
kamatera.debian_11: output will be in this color.

==> kamatera.debian_11: Creating server ...
==> kamatera.debian_11: error response from Kamatera API (400): map[json_decode_error:<nil> message:General Error. (1)]
Build 'kamatera.debian_11' errored after 1 minute 5 seconds: error response from Kamatera API (400): map[json_decode_error:<nil> message:General Error. (1)]

==> Wait completed after 1 minute 5 seconds

==> Some builds didn't complete successfully and had errors:
--> kamatera.debian_11: error response from Kamatera API (400): map[json_decode_error:<nil> message:General Error. (1)]

==> Builds finished but no artifacts were created.`

**Comment by OriHoch** [comment]
Thanks, this is an error from the Kamatera API not related directly to the packer plugin. The relevant error is `General Error. (1)`

I will try to reproduce it as well but you should also contact Kamatera support about this error at [support@kamatera.com](mailto:support@kamatera.com)

I also opened an issue to improve the user experience for this kind of errors - #49

**Comment by strelok899** [comment]
contacted the support they not actually help ....

**Comment by OriHoch** [comment]
issue is being investigated with our R&D team and will response soon

**Comment by strelok899** [comment]
Any news?

**Comment by OriHoch** [comment]
hi, sorry for the delay, still waiting for a response from R&D team

**Comment by OriHoch** [comment]
the problem does not reproduce, feel free to reopen if problem persists
